name: registro_ventas_nuevo
description: Una aplicación Flutter para registrar ventas e inventario de celulares.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 
  connectivity_plus: ^4.0.2  
  
  #Login
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^2.15.1  
  cloud_firestore: ^4.9.1 
  firebase_auth: ^4.9.0  

  # Escaneo de código de barras
  mobile_scanner: ^3.4.1  

  # Manejo de fechas y horas
  intl: ^0.18.1  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2 

flutter:
  uses-material-design: true
  assets:
    - assets/originales_cellstore_logo.jpg